### ISSUE TITLE
Susi interface in a Linux text Browser?

### ISSUE THREAD

**Issue by smokingwheels** [fossasia/asksusi.com#16]
What about having Susi running in a Linux text Browser? [Here](https://twitter.com/smokingwheels/status/764035564832116736)

I am not sure really what the problem is but I cant seem to get it to work.

**Comment by SpEcHiDe** [comment]
I think the problem is JavaScript being disabled by default in most text based browsers. 
Please read here: http://elinks.or.cz/documentation/manual.html#ecmascript or we may need to think some other method to show a "Switch to modern browser warning" when opened on text based browsers! 

I think, this can be done by adding a <noscript> tag!
